### ISSUE TITLE
TypeError: Cannot read property 'aggsType' of undefined

### ISSUE THREAD

**Issue by kalwar** [jettro/elasticsearch-gui#98]
When creating aggregations.. and clicking on the aggregation link throws this error:

Cannot read property 'aggsType' of undefined
    at filterChosenAggregatePart (http://localhost/test/assets/js/elasticsearch-gui.js:2428:50)
    at SearchCtrl.doSearch (http://localhost/test/assets/js/elasticsearch-gui.js:2173:26)
    at SearchCtrl.restartSearch (http://localhost/test/assets/js/elasticsearch-gui.js:2155:16)
    at http://localhost/test/assets/libs/angular.min.js:200:303
    at f (http://localhost/test/assets/libs/angular.min.js:217:74)
    at n.$eval (http://localhost/test/assets/libs/angular.min.js:126:250)
    at n.$apply (http://localhost/test/assets/libs/angular.min.js:126:476)
    at HTMLButtonElement.<anonymous> (http://localhost/test/assets/libs/angular.min.js:217:126)
    at HTMLButtonElement.n.event.dispatch (http://localhost/test/js_new/js/jquery-2.1.4.min.js:3:6466)
    at HTMLButtonElement.r.handle (http://localhost/test/js_new/js/jquery-2.1.4.min.js:3:3241) undefined(anonymous function) @ angular.min.js:102(anonymous function) @ angular.min.js:76(anonymous function) @ elasticsearch-gui.js:1037n.$apply @ angular.min.js:126(anonymous function) @ angular.min.js:217n.event.dispatch @ jquery-2.1.4.min.js:3r.handle @ jquery-2.1.4.min.js:3
angular.min.js:102 undefined

**Comment by jettro** [comment]
Can you please tell me what version of the plugin you are using and what version of elasticsearch

**Comment by kalwar** [comment]
I am using ES 2.2 and the plugin is the latest master version.

**Comment by jettro** [comment]
I fixed the bug, should be able to use this feature again on master
